fix makepkg

diff --git a/scripts/makepkg b/scripts/makepkg
--- a/scripts/makepkg
+++ b/scripts/makepkg
@@ -715,6 +715,7 @@ fi
 
 	sudo chown root:root -R ./
 	dpkg-deb --build ./ $pkg_file
+	cp  "$pkg_file"  "$IRBDIR"/
 	#shopt -u -o pipefail
 
 	
@@ -836,10 +837,12 @@ install_package() {
 	remove_deps || return $?
 	RMDEPS=0
 
+
+
 	if (( ! SPLITPKG )); then
-		msg "$(gettext "Installing package %s with %s...")" "$pkgname" "$PACMAN -U"
+		msg "$(gettext "Installing package %s with %s...")" "$pkgname" "dpkg"
 	else
-		msg "$(gettext "Installing %s package group with %s...")" "$pkgbase" "$PACMAN -U"
+		msg "$(gettext "Installing %s package group with %s...")" "$pkgbase" "dpkg"
 	fi
 
 	local fullver pkgarch pkg pkglist
@@ -849,14 +852,16 @@ install_package() {
 	for pkg in ${pkgname[@]}; do
 		fullver=$(get_full_version)
 		pkgarch=$(get_pkg_arch $pkg)
-		pkglist+=("$PKGDEST/${pkg}-${fullver}-${pkgarch}${PKGEXT}")
+		pkglist+=("$PKGDEST/${pkg}-${fullver}-amd64.deb")
 
 		if [[ -f "$PKGDEST/${pkg}-debug-${fullver}-${pkgarch}${PKGEXT}" ]]; then
 			pkglist+=("$PKGDEST/${pkg}-debug-${fullver}-${pkgarch}${PKGEXT}")
 		fi
 	done
 
-	if ! run_pacman -U "${pkglist[@]}"; then
+
+
+	if ! sudo dpkg -i  "${pkglist[@]}"; then
 		warning "$(gettext "Failed to install built package(s).")"
 		return $E_INSTALL_FAILED
 	fi
@@ -1017,6 +1022,168 @@ There is NO WARRANTY, to the extent permitted by law.\n")"
 
 # PROGRAM START
 
+parseoptsirb() {
+	local opt= optarg= i= shortopts=$1
+	local -a longopts=() unused_argv=()
+
+	shift
+	while [[ $1 && $1 != '--' ]]; do
+		longopts+=("$1")
+		shift
+	done
+	shift
+
+	longoptmatch() {
+		local o longmatch=()
+		for o in "${longopts[@]}"; do
+			if [[ ${o%[:?]} = "$1" ]]; then
+				longmatch=("$o")
+				break
+			fi
+			[[ ${o%[:?]} = "$1"* ]] && longmatch+=("$o")
+		done
+
+		case ${#longmatch[*]} in
+			1)
+				# success, override with opt and return arg req (0 == none, 1 == required, 2 == optional)
+				opt=${longmatch%[:?]}
+				case $longmatch in
+					*:)  return 1 ;;
+					*\?) return 2 ;;
+					*)   return 0 ;;
+				esac
+				;;
+			0)
+				# fail, no match found
+				return 255 ;;
+			*)
+				# fail, ambiguous match
+				printf "${0##*/}: $(gettext "option '%s' is ambiguous; possibilities:")" "--$1"
+				printf " '%s'" "${longmatch[@]%[:?]}"
+				printf '\n'
+				return 254 ;;
+		esac >&2
+	}
+
+	while (( $# )); do
+		case $1 in
+			--) # explicit end of options
+				shift
+				break
+				;;
+			-[!-]*) # short option
+				for (( i = 1; i < ${#1}; i++ )); do
+					opt=${1:i:1}
+
+					case $shortopts in
+						# option requires optarg
+						*$opt:*)
+							# if we're not at the end of the option chunk, the rest is the optarg
+							if (( i < ${#1} - 1 )); then
+								OPTRET+=("-$opt" "${1:i+1}")
+								break
+							# if we're at the end, grab the the next positional, if it exists
+							elif (( i == ${#1} - 1 && $# > 1 )); then
+								OPTRET+=("-$opt" "$2")
+								shift
+								break
+							# parse failure
+							else
+								printf "${0##*/}: $(gettext "option requires an argument") -- '%s'\n" "$opt" >&2
+								OPTRET=(--)
+								return 1
+							fi
+							;;
+						# option's optarg is optional
+						*$opt\?*)
+							# if we're not at the end of the option chunk, the rest is the optarg
+							if (( i < ${#1} - 1 )); then
+								OPTRET+=("-$opt=${1:i+1}")
+								break
+							# option has no optarg
+							else
+								OPTRET+=("-$opt")
+							fi
+							;;
+						# option has no optarg
+						*$opt*)
+							OPTRET+=("-$opt")
+							;;
+						# option doesn't exist
+						*)
+							printf "${0##*/}: $(gettext "invalid option") -- '%s'\n" "$opt" >&2
+							OPTRET=(--)
+							return 1
+							;;
+					esac
+				done
+				;;
+			--?*=*|--?*) # long option
+				IFS='=' read -r opt optarg <<< "${1#--}"
+				longoptmatch "$opt"
+				case $? in
+					0)
+						# parse failure
+						if [[ $1 = *=* ]]; then
+							printf "${0##*/}: $(gettext "option '%s' does not allow an argument")\n" "--$opt" >&2
+							OPTRET=(--)
+							return 1
+						# --longopt
+						else
+							OPTRET+=("--$opt")
+						fi
+						;;
+					1)
+						# --longopt=optarg
+						if [[ $1 = *=* ]]; then
+							OPTRET+=("--$opt" "$optarg")
+						# --longopt optarg
+						elif (( $# > 1 )); then
+							OPTRET+=("--$opt" "$2" )
+							shift
+						# parse failure
+						else
+							printf "${0##*/}: $(gettext "option '%s' requires an argument")\n" "--$opt" >&2
+							OPTRET=(--)
+							return 1
+						fi
+						;;
+					2)
+						# --longopt=optarg
+						if [[ $1 = *=* ]]; then
+							OPTRET+=("--$opt=$optarg")
+						# --longopt
+						else
+							OPTRET+=("--$opt")
+						fi
+						;;
+					254)
+						# ambiguous option -- error was reported for us by longoptmatch()
+						OPTRET=(--)
+						return 1
+						;;
+					255)
+						# parse failure
+						printf "${0##*/}: $(gettext "invalid option") '--%s'\n" "$opt" >&2
+						OPTRET=(--)
+						return 1
+						;;
+				esac
+				;;
+			*) # non-option arg encountered, add it as a parameter
+				unused_argv+=("$1")
+				;;
+		esac
+		shift
+	done
+
+	# add end-of-opt terminator and any leftover positional parameters
+	OPTRET+=('--' "${unused_argv[@]}" "$@")
+	unset longoptmatch
+
+	return 0
+}
+
 # ensure we have a sane umask set
 umask 0022
 
@@ -1030,7 +1197,7 @@ fi
 ARGLIST=("$@")
 
 # Parse Command Line Options.
-OPT_SHORT="AcCdD:efFghiLmop:rRsSVI"
+OPT_SHORT="AcCdI:D:efFghiLmop:rRsSV"
 OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'dir:' 'force' 'geninteg'
           'help' 'holdver' 'ignorearch' 'install' 'key:' 'log' 'noarchive' 'nobuild'
           'nocolor' 'nocheck' 'nodeps' 'noextract' 'noprepare' 'nosign' 'packagelist'
@@ -1040,9 +1207,10 @@ OPT_LONG=('allsource' 'check' 'clean' 'cleanbuild' 'config:' 'dir:' 'force' 'gen
 # Pacman Options
 OPT_LONG+=('asdeps' 'noconfirm' 'needed' 'noprogressbar')
 
-if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
-	exit $E_INVALID_OPTION
+if ! parseoptsirb "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+	echo $E_INVALID_OPTION
 fi
+
 set -- "${OPTRET[@]}"
 unset OPT_SHORT OPT_LONG OPTRET
 
@@ -1063,7 +1231,7 @@ while true; do
 		--config)         shift; MAKEPKG_CONF=$1 ;;
 		-d|--nodeps)      NODEPS=1 ;;
 		-D|--dir)         shift; CHDIR=$1 ;;
-		-I|--dpkg)         shift; DEBDIR=$1 ;;
+		-I|--dpkg)     shift;  IRBDIR=$1 ;;
 		-e|--noextract)   NOEXTRACT=1 ;;
 		-f|--force)       FORCE=1 ;;
 		-F)               INFAKEROOT=1 ;;
@@ -1100,6 +1268,7 @@ while true; do
 	esac
 	shift
 done
+
 
 # attempt to consume any extra argv as environment variables. this supports
 # overriding (e.g. CC=clang) as well as overriding (e.g. CFLAGS+=' -g').
